### PR TITLE
Dynamically add and remove nodes

### PR DESCRIPTION
**Pull request by brysgo**
Here is an attempt at #16

### CODE REVIEW

**Comment by brysgo** [comment]
Doesn't redraw if it is hidden and put back on the page :-(

**Comment by Radivarig** [comment]
Tried the example with your branch and nothing shows up, am I missing something?

**Comment by brysgo** [comment]
Hmm... It worked for me. Let me try tomorrow and get back to you.

**Comment by Radivarig** [comment]
I've managed to get it showing, by first double-clicking then dragging the canvas.

**Comment by Radivarig** [comment]
I got it showing by clicking few times and dragging.

**Comment by Radivarig** [comment]
Would be great to have a way of specifying a position for the new node like mouse position

**Comment by brysgo** [comment]
@Radivarig - what browser are you using, it works fine for me: http://www.brysgo.com/react-graph-vis/

**Comment by Radivarig** [comment]
I discarded the example and used just this fork. Adding nodes works great, graph is not reset. Should get merged

**Comment by brysgo** [comment]
@Radivarig - do you need anything from me first?

**Comment by Radivarig** [comment]
@brysgo can you add patching for when events change as well?

**Comment by Radivarig** [comment]
@brysgo could you add the same for changed events without rerender?
Would `eventsChange` on every props.events object ref change be too heavy? (for situations like `options={{/*newObj*/}}` in which case something like `eventsTimestamp` can be passed to trigger it)

**Comment by brysgo** [comment]
@Radivarig - certainly

**Comment by crubier** [comment]
@brysgo , thank you for this contribution. Is this ready to get merged ? How can I test it ? THank you very much !

**Comment by brysgo** [comment]
@crubier - Let me make the the change @Radivarig suggested first.

**Comment by Radivarig** [comment]
@brysgo maybe this approach can solve hierarchy issue as well? #18

**Comment by brysgo** [comment]
@Radivarig - I'm pretty strapped for time right now, do you think you could make a PR to my fork and then we can update this PR?

**Comment by Radivarig** [comment]
@brysgo sure, I added a PR for events. Will look into hierarchy issue

**Comment by brysgo** [comment]
@Radivarig - did it fix your issue?

**Comment by Radivarig** [comment]
It doesn't get reset if I set `options.physics.enabled = false`. I'd say we can close this PR and deal with hierarchy issue separately.

**Comment by brysgo** [comment]
Does that mean you think it is okay to merge?

**Comment by Radivarig** [comment]
Yep, @crubier. I'll continue with my findings about hierarchy issue in #18

**Comment by Radivarig** [comment]
If we compare the optionsChange by string instead by reference it will change only when its values change. Also, if not checked by string, it will always be difference by reference for cases like `options={{/*new object*/}}`, so only global or store based options will stay unchanged by reference.

Checking by string also partially solves the hierarchy issue (partially as if I don't change options object, for example `multiselect: toggledBySomething` it wont call `network.setOptions` which will not reset node positions).

@brysgo what do you think? I can add another PR to your branch.

**Comment by crubier** [comment]
@Radivarig , so in the end, should I merge this PR ?

**Comment by Radivarig** [comment]
@crubier yes this can be merged. Hierarchy issue is opened on visjs and closed here.

**Comment by crubier** [comment]
Ok thanks !

**Pull request merged**
