### PR TITLE
Update element to support all viz.js options - numerous updates

### PR DESCRIPTION
**Pull request by HosseinAgha**
- update viz.js
- migrate for new viz api
- rewrite `shouldComponentUpdate` to support non `immutable` props

### CODE REVIEW

**Comment by crubier** [comment]
Nice ! Did you test this ?

**Comment by HosseinAgha** [comment]
Yes, all tested. 
  but it has some breaking changes I think so I had to bump the package version.

**Comment by crubier** [comment]
Ok, could you update the readme as well then please ? Just some basic documentation in a few lines

**Comment by HosseinAgha** [comment]
Sure, will update it asap.

**Comment by HosseinAgha** [comment]
@crubier Just updated the readme

**Comment by crubier** [comment]
Excellent ! Merged, thank you !

**Pull request merged**
